version: 1.0.{build}
build_script:
- ps: >-
    $AssemblyFile = "AssemblyInfo.cs"

    $RegularExpression = [regex] '^\[assembly: AssemblyVersion\(\"(\d*\.\d*\.\d*)\.\d*\"\)\]$'

    $FileContent = Get-Content $AssemblyFile

    foreach($content in $FileContent) {
      $match = [System.Text.RegularExpressions.Regex]::Match($content, $RegularExpression)
      if($match.Success) {
        $ver = $match.groups[1].value
        break;
      }
    }

    Update-AppveyorBuild -Version ("{0}.{1}" -f $ver, $env:APPVEYOR_BUILD_NUMBER)

    $env:PATH = C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319;$env:PATH

    csc /out:$env:APPVEYOR_PROJECT_NAME.exe /recurse:*.cs

    7z a $env:APPVEYOR_PROJECT_NAME-v$env:APPVEYOR_BUILD_VERSION.zip *.exe *.md
artifacts:
- path: '*.zip'
  name: Zip
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: $(appveyor_project_name)-v$(appveyor_build_version)
  description: Automatic rebuild
  auth_token:
    secure: CePfctnBFd3iDwgVWlGOD6mfxQZrNBHK7IpsCK/deo2vHxA3lTr2nRnhbqpKqchQ
  artifact: Zip
  draft: true
  force_update: true
